"use strict";

const path = require("node:path");
const fs = require("node:fs");
const crypto = require("node:crypto");
const express = require("express");
const multer = require("multer");
const { Pool } = require("pg");
const ExcelJS = require("exceljs");

try {
  process.loadEnvFile(path.join(__dirname, ".env"));
} catch {
  /* .env optionnel */
}

const PORT = Number(process.env.PORT) || 3000;
const DATA_DIR = path.resolve(__dirname, process.env.DATA_DIR || "data");
const UPLOAD_DIR = path.join(DATA_DIR, "uploads");
const MAX_FILE_MB = Number(process.env.MAX_FILE_MB) || 5;
const REG_DEADLINE = new Date(process.env.REG_DEADLINE || "2026-10-18T23:59:59+01:00");
const TOKEN_TTL_MS = 8 * 60 * 60 * 1000;

let ADMIN_PASSWORD = process.env.ADMIN_PASSWORD;
if (!ADMIN_PASSWORD) {
  ADMIN_PASSWORD = crypto.randomBytes(9).toString("base64url");
  console.warn(`[admin] ADMIN_PASSWORD non défini - mot de passe temporaire : ${ADMIN_PASSWORD}`);
}

fs.mkdirSync(UPLOAD_DIR, { recursive: true });

/* ------------------------------------------------------------------ */
/* Base de données                                                     */
/* ------------------------------------------------------------------ */
const DATABASE_URL = process.env.DATABASE_URL || "";
if (!DATABASE_URL) {
  console.error("DATABASE_URL manquant. Sur Railway : ajoutez PostgreSQL et liez DATABASE_URL au service web.");
  process.exit(1);
}
const pool = new Pool({
  connectionString: DATABASE_URL,
  ssl: process.env.PGSSL === "disable" ? false : DATABASE_URL.includes("localhost") || DATABASE_URL.includes("127.0.0.1") ? false : { rejectUnauthorized: false },
});

function toPg(sql) {
  let n = 0;
  return String(sql).replace(/COLLATE NOCASE/gi, "").replace(/\?/g, () => `$${++n}`);
}

const db = {
  async exec(sql) {
    await pool.query(sql);
  },
  prepare(sql) {
    return {
      async get(...params) {
        const r = await pool.query(toPg(sql), params);
        return r.rows[0];
      },
      async all(...params) {
        const r = await pool.query(toPg(sql), params);
        return r.rows;
      },
      async run(...params) {
        let text = toPg(sql);
        if (/^\s*insert\s+/i.test(sql) && !/returning\b/i.test(sql)) text += " RETURNING id";
        const r = await pool.query(text, params);
        return { lastInsertRowid: r.rows[0] && r.rows[0].id, changes: r.rowCount };
      },
    };
  },
};

async function initDb() {
  await db.exec(`
  CREATE TABLE IF NOT EXISTS registrations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref TEXT UNIQUE NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'received',
    track TEXT NOT NULL,
    challenge INTEGER NOT NULL,
    title TEXT NOT NULL,
    leader_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    institution TEXT,
    city TEXT,
    team_size INTEGER NOT NULL,
    lang TEXT,
    file_path TEXT,
    file_original TEXT,
    file_size INTEGER,
    payload TEXT NOT NULL,
    admin_note TEXT DEFAULT '',
    ip_hash TEXT
  );
  CREATE INDEX IF NOT EXISTS idx_reg_email ON registrations(email);
  CREATE TABLE IF NOT EXISTS messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TEXT NOT NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT,
    message TEXT NOT NULL,
    handled INTEGER NOT NULL DEFAULT 0
  );
  CREATE TABLE IF NOT EXISTS jurors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TEXT NOT NULL
  );
  CREATE TABLE IF NOT EXISTS scores (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_id INTEGER NOT NULL,
    juror_id INTEGER NOT NULL,
    scores TEXT NOT NULL,
    comment TEXT NOT NULL DEFAULT '',
    updated_at TEXT NOT NULL,
    UNIQUE(registration_id, juror_id)
  );
`);
  async function addColumn(table, column, definition) {
    const cols = await db.prepare(
      `SELECT column_name AS name FROM information_schema.columns WHERE table_name = ?`
    ).all(table);
    if (!cols.some((c) => c.name === column)) await db.exec(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`);
  }
  await addColumn("jurors", "email", "TEXT");
  await addColumn("jurors", "password_hash", "TEXT");
  await addColumn("jurors", "track", "TEXT");
  await db.exec("CREATE UNIQUE INDEX IF NOT EXISTS idx_jurors_email ON jurors(email)");
}

/* ------------------------------------------------------------------ */
/* Référentiels                                                        */
/* ------------------------------------------------------------------ */
const TRACKS = ["idea", "lab", "scale"];
const CHALLENGES = [1, 2, 3, 4, 5, 6];
const STATUSES = ["received", "review", "shortlisted", "finalist", "winner", "rejected"];
const PROFILES = ["student", "phd", "researcher", "startup", "professional", "other"];
const MATURITY = ["idea", "concept", "poc", "prototype", "mvp", "market"];
const NEEDS = ["mentoring", "ip", "prototyping", "business", "funding", "market", "network", "incubation"];
const TERRITORIES = ["gon", "lse", "dod", "all"];
const ALLOWED_EXT = [".pdf", ".ppt", ".pptx"];
const CRITERIA = [
  "Pertinence pour les Provinces du Sud",
  "Caractère innovant",
  "Création de valeur",
  "Faisabilité",
  "Potentiel de marché",
  "Emploi et entrepreneuriat",
  "Impact territorial et durabilité",
  "Qualité de l'équipe",
];

function juryAverage(arr) {
  if (!Array.isArray(arr) || arr.length !== CRITERIA.length) return null;
  if (arr.some((n) => !Number.isInteger(n) || n < 1 || n > 5)) return null;
  return arr.reduce((a, b) => a + b, 0) / arr.length;
}

function hashPassword(password) {
  const salt = crypto.randomBytes(16).toString("hex");
  return `${salt}:${crypto.scryptSync(password, salt, 32).toString("hex")}`;
}

function checkPassword(password, stored) {
  if (!stored || !stored.includes(":")) return false;
  const [salt, hash] = stored.split(":");
  const got = crypto.scryptSync(String(password), salt, 32);
  const ref = Buffer.from(hash, "hex");
  return got.length === ref.length && crypto.timingSafeEqual(got, ref);
}

function decodeName(name) {
  if (!name || !/[ÃÂâ€]/.test(name)) return name || "";
  const fixed = Buffer.from(name, "latin1").toString("utf8");
  return fixed.includes("\uFFFD") ? name : fixed;
}

async function averagesByRegistration() {
  const groups = new Map();
  const rows = await db
    .prepare(
      `SELECT s.registration_id, s.scores
       FROM scores s
       JOIN jurors j ON j.id = s.juror_id
       JOIN registrations r ON r.id = s.registration_id
       WHERE j.track = r.track`
    )
    .all();
  for (const row of rows) {
    let parsed;
    try {
      parsed = JSON.parse(row.scores);
    } catch {
      continue;
    }
    const avg = juryAverage(parsed);
    if (avg == null) continue;
    const list = groups.get(row.registration_id) || [];
    list.push(avg);
    groups.set(row.registration_id, list);
  }
  const out = new Map();
  for (const [id, avgs] of groups) {
    out.set(id, {
      avg: Math.round((avgs.reduce((a, b) => a + b, 0) / avgs.length) * 10) / 10,
      n: avgs.length,
    });
  }
  return out;
}

/* ------------------------------------------------------------------ */
/* Utilitaires                                                         */
/* ------------------------------------------------------------------ */
const now = () => new Date().toISOString();
const hashIp = (ip) => crypto.createHash("sha256").update(String(ip) + "sic2026").digest("hex").slice(0, 16);

function str(v, max = 500) {
  if (typeof v !== "string") return "";
  return v.replace(/\u0000/g, "").trim().slice(0, max);
}

function isEmail(v) {
  return /^[^\s@]{1,64}@[^\s@]{1,190}\.[^\s@]{2,}$/.test(v);
}

function isPhone(v) {
  return /^\+?[0-9 ().-]{8,20}$/.test(v);
}

function isUrl(v) {
  try {
    const u = new URL(v);
    return u.protocol === "https:" || u.protocol === "http:";
  } catch {
    return false;
  }
}

function makeRef() {
  const n = crypto.randomInt(0, 36 ** 5).toString(36).toUpperCase().padStart(5, "0");
  return `SIC26-${n}`;
}

function parseJsonField(v, fallback) {
  if (typeof v !== "string" || !v) return fallback;
  try {
    return JSON.parse(v);
  } catch {
    return fallback;
  }
}

function asArray(v) {
  if (Array.isArray(v)) return v;
  if (typeof v === "string" && v) return [v];
  return [];
}

/** Limiteur de débit en mémoire (fenêtre glissante simple). */
function rateLimit({ windowMs, max }) {
  const hits = new Map();
  setInterval(() => {
    const t = Date.now();
    for (const [k, arr] of hits) {
      const kept = arr.filter((x) => t - x < windowMs);
      if (kept.length) hits.set(k, kept);
      else hits.delete(k);
    }
  }, windowMs).unref();
  return async (req, res, next) => {
    const t = Date.now();
    const arr = (hits.get(req.ip) || []).filter((x) => t - x < windowMs);
    if (arr.length >= max) {
      return res.status(429).json({ ok: false, error: "rate_limited" });
    }
    arr.push(t);
    hits.set(req.ip, arr);
    next();
  };
}

/* ------------------------------------------------------------------ */
/* Upload                                                              */
/* ------------------------------------------------------------------ */
const upload = multer({
  storage: multer.diskStorage({
    destination: UPLOAD_DIR,
    filename: (_req, file, cb) => {
      const ext = path.extname(file.originalname).toLowerCase();
      cb(null, `${Date.now()}-${crypto.randomBytes(6).toString("hex")}${ext}`);
    },
  }),
  limits: { fileSize: MAX_FILE_MB * 1024 * 1024, files: 1, fields: 80 },
  fileFilter: (_req, file, cb) => {
    const ext = path.extname(file.originalname).toLowerCase();
    if (!ALLOWED_EXT.includes(ext)) return cb(new Error("bad_file_type"));
    cb(null, true);
  },
});

/* ------------------------------------------------------------------ */
/* Validation d'une candidature                                        */
/* ------------------------------------------------------------------ */
function validateRegistration(body, file) {
  const errors = {};
  const req = (key, val, ok = Boolean(val)) => {
    if (!ok) errors[key] = "invalid";
  };

  const leader = {
    first_name: str(body.first_name, 80),
    last_name: str(body.last_name, 80),
    email: str(body.email, 200).toLowerCase(),
    phone: str(body.phone, 30),
    gender: str(body.gender, 20),
    city: str(body.city, 80),
    profile: str(body.profile, 30),
    institution: str(body.institution, 200),
    position: str(body.position, 120),
    linkedin: str(body.linkedin, 300),
  };
  req("first_name", leader.first_name);
  req("last_name", leader.last_name);
  req("email", leader.email, isEmail(leader.email));
  req("phone", leader.phone, isPhone(leader.phone));
  req("city", leader.city);
  req("institution", leader.institution);
  const PROFILES = ["researcher", "student", "startup"];
  req("profile", leader.profile, PROFILES.includes(leader.profile));
  leader.study_level = str(body.study_level, 20);
  leader.training_title = str(body.training_title, 160);
  if (leader.profile === "student") {
    req("study_level", leader.study_level, ["master", "doctorate", "engineer"].includes(leader.study_level));
    req("training_title", leader.training_title, leader.training_title.length >= 2);
  }
  if (leader.linkedin) req("linkedin", leader.linkedin, isUrl(leader.linkedin));

  const teamSize = Number.parseInt(body.team_size, 10) || 1;
  const members = parseJsonField(body.members, [])
    .slice(0, 4)
    .map((m) => ({
      name: str(m && m.name, 120),
      email: str(m && m.email, 200).toLowerCase(),
      role: str(m && m.role, 120),
      institution: str(m && m.institution, 200),
      profile: str(m && m.profile, 20),
      study_level: str(m && m.study_level, 20),
      training_title: str(m && m.training_title, 160),
    }))
    .filter((m) => m.name);
  req("team_size", teamSize, teamSize >= 1 && teamSize <= 5);
  members.forEach((m, i) => {
    if (m.email && !isEmail(m.email)) errors[`member_${i}_email`] = "invalid";
  });

  const project = {
    team_name: str(body.team_name, 120),
    team_acronym: str(body.team_acronym, 30),
    track: str(body.track, 10),
    challenge: Number.parseInt(body.challenge, 10),
    title: str(body.title, 150),
    acronym: str(body.acronym, 30),
    summary: str(body.summary, 6000),
    problem: str(body.problem, 1500),
    solution: str(body.solution, 1500),
    innovation: str(body.innovation, 1200),
    target: str(body.target, 800),
    impact: str(body.impact, 1200),
    territories: asArray(parseJsonField(body.territories, [])).filter((t) => TERRITORIES.includes(t)),
    maturity: str(body.maturity, 20),
    trl: body.trl ? Number.parseInt(body.trl, 10) : null,
    ip_status: str(body.ip_status, 30),
    startup_name: str(body.startup_name, 150),
    startup_year: str(body.startup_year, 4),
    startup_legal: str(body.startup_legal, 60),
    website: str(body.project_website, 300),
    video_url: str(body.video_url, 300),
    needs: asArray(parseJsonField(body.needs, [])).filter((n) => NEEDS.includes(n)),
    heard_from: str(body.heard_from, 60),
  };
  req("track", project.track, TRACKS.includes(project.track));
  req("challenge", project.challenge, CHALLENGES.includes(project.challenge));
  req("title", project.title, project.title.length >= 3);
  const summaryWords = project.summary.trim() ? project.summary.trim().split(/\s+/).length : 0;
  req("summary", project.summary, project.summary.length >= 40 && summaryWords <= 700);
  if (project.video_url) req("video_url", project.video_url, isUrl(project.video_url));
  if (project.website) req("project_website", project.website, isUrl(project.website));

  const consents = {
    rules: body.consent_rules === "true" || body.consent_rules === "on",
    data: body.consent_data === "true" || body.consent_data === "on",
    media: body.consent_media === "true" || body.consent_media === "on",
  };
  req("consent_rules", consents.rules);
  req("consent_data", consents.data);
  req("consent_media", consents.media);

  return { errors, leader, members, teamSize, project, consents };
}

/* ------------------------------------------------------------------ */
/* Application                                                         */
/* ------------------------------------------------------------------ */
const app = express();
app.set("trust proxy", 1);
app.disable("x-powered-by");

app.use((_req, res, next) => {
  res.setHeader("X-Content-Type-Options", "nosniff");
  res.setHeader("Referrer-Policy", "strict-origin-when-cross-origin");
  res.setHeader("X-Frame-Options", "SAMEORIGIN");
  res.setHeader("Permissions-Policy", "camera=(), microphone=(), geolocation=()");
  next();
});

app.use(express.json({ limit: "100kb" }));
app.use(
  express.static(path.join(__dirname, "public"), {
    extensions: ["html"],
    setHeaders: (res) => res.setHeader("Cache-Control", "no-cache"),
  })
);

app.get("/api/config", (_req, res) => {
  res.json({
    registrationOpen: Date.now() < REG_DEADLINE.getTime(),
    deadline: REG_DEADLINE.toISOString(),
    maxFileMb: MAX_FILE_MB,
    allowedExt: ALLOWED_EXT,
  });
});

app.post(
  "/api/register",
  rateLimit({ windowMs: 15 * 60 * 1000, max: 8 }),
  async (req, res, next) => {
    upload.single("project_file")(req, res, (err) => {
      if (!err) return next();
      const code = err.code === "LIMIT_FILE_SIZE" ? "file_too_large" : err.message === "bad_file_type" ? "bad_file_type" : "upload_error";
      res.status(400).json({ ok: false, error: code });
    });
  },
  async (req, res) => {
    const cleanup = () => req.file && fs.rm(req.file.path, { force: true }, () => {});

    if (str(req.body.website_hp)) {
      cleanup();
      return res.json({ ok: true, ref: makeRef() });
    }
    if (Date.now() >= REG_DEADLINE.getTime()) {
      cleanup();
      return res.status(403).json({ ok: false, error: "closed" });
    }

    const v = validateRegistration(req.body, req.file);
    if (Object.keys(v.errors).length) {
      cleanup();
      return res.status(422).json({ ok: false, error: "validation", fields: v.errors });
    }

    const dup = await db
      .prepare("SELECT ref FROM registrations WHERE email = ? AND lower(title) = lower(?)")
      .get(v.leader.email, v.project.title);
    if (dup) {
      cleanup();
      return res.status(409).json({ ok: false, error: "duplicate", ref: dup.ref });
    }

    const payload = { leader: v.leader, members: v.members, project: v.project, consents: v.consents };
    const ts = now();
    let ref;
    for (let i = 0; i < 5; i++) {
      ref = makeRef();
      try {
        await db.prepare(
          `INSERT INTO registrations
           (ref, created_at, updated_at, track, challenge, title, leader_name, email, phone, institution, city,
            team_size, lang, file_path, file_original, file_size, payload, ip_hash)
           VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`
        ).run(
          ref, ts, ts, v.project.track, v.project.challenge, v.project.title,
          `${v.leader.first_name} ${v.leader.last_name}`, v.leader.email, v.leader.phone,
          v.leader.institution, v.leader.city, v.teamSize, str(req.body.lang, 5) || "fr",
          path.basename(req.file ? req.file.path : "") || null, req.file ? decodeName(str(req.file.originalname, 200)) : null, req.file ? req.file.size : null,
          JSON.stringify(payload), hashIp(req.ip)
        );
        break;
      } catch (e) {
        if (e.code !== "23505" && !String(e.message).includes("UNIQUE") || i === 4) {
          cleanup();
          console.error(e);
          return res.status(500).json({ ok: false, error: "server" });
        }
      }
    }
    console.log(`[inscription] ${ref} - ${v.project.title}`);
    res.status(201).json({ ok: true, ref });
  }
);

app.post("/api/contact", rateLimit({ windowMs: 15 * 60 * 1000, max: 5 }), async (req, res) => {
  const b = req.body || {};
  if (str(b.website_hp)) return res.json({ ok: true });
  const name = str(b.name, 120);
  const email = str(b.email, 200).toLowerCase();
  const subject = str(b.subject, 150);
  const message = str(b.message, 3000);
  const fields = {};
  if (!name) fields.name = "invalid";
  if (!isEmail(email)) fields.email = "invalid";
  if (message.length < 10) fields.message = "invalid";
  if (Object.keys(fields).length) return res.status(422).json({ ok: false, error: "validation", fields });
  await db.prepare("INSERT INTO messages (created_at, name, email, subject, message) VALUES (?,?,?,?,?)").run(now(), name, email, subject, message);
  res.status(201).json({ ok: true });
});

/* ------------------------------------------------------------------ */
/* Administration                                                      */
/* ------------------------------------------------------------------ */
const tokens = new Map();

function requireAdmin(req, res, next) {
  const h = req.get("authorization") || "";
  const token = h.startsWith("Bearer ") ? h.slice(7) : "";
  const exp = tokens.get(token);
  if (!exp || exp < Date.now()) {
    tokens.delete(token);
    return res.status(401).json({ ok: false, error: "unauthorized" });
  }
  next();
}

app.post("/api/admin/login", rateLimit({ windowMs: 15 * 60 * 1000, max: 10 }), async (req, res) => {
  const pwd = Buffer.from(str(req.body && req.body.password, 200));
  const ref = Buffer.from(ADMIN_PASSWORD);
  const ok = pwd.length === ref.length && crypto.timingSafeEqual(pwd, ref);
  if (!ok) return res.status(401).json({ ok: false, error: "bad_password" });
  const token = crypto.randomBytes(32).toString("hex");
  tokens.set(token, Date.now() + TOKEN_TTL_MS);
  res.json({ ok: true, token });
});

app.post("/api/admin/logout", requireAdmin, async (req, res) => {
  tokens.delete((req.get("authorization") || "").slice(7));
  res.json({ ok: true });
});

function rowToRegistration(r) {
  return { ...r, file_original: decodeName(r.file_original), payload: JSON.parse(r.payload), file_path: undefined, ip_hash: undefined, password_hash: undefined };
}

app.get("/api/admin/stats", requireAdmin, async (_req, res) => {
  const total = (await db.prepare("SELECT COUNT(*) AS n FROM registrations").get()).n;
  const participants = (await db.prepare("SELECT COALESCE(SUM(team_size),0) AS n FROM registrations").get()).n;
  const byTrack = await db.prepare("SELECT track AS k, COUNT(*) AS n FROM registrations GROUP BY track").all();
  const byChallenge = await db.prepare("SELECT challenge AS k, COUNT(*) AS n FROM registrations GROUP BY challenge").all();
  const byStatus = await db.prepare("SELECT status AS k, COUNT(*) AS n FROM registrations GROUP BY status").all();
  const byDayRows = await db
    .prepare("SELECT substr(created_at,1,10) AS k, COUNT(*) AS n FROM registrations GROUP BY k ORDER BY k DESC LIMIT 30")
    .all();
  const byDay = byDayRows.reverse();
  res.json({ ok: true, total, participants, byTrack, byChallenge, byStatus, byDay, unreadMessages: 0 });
});

app.get("/api/admin/registrations", requireAdmin, async (req, res) => {
  const where = [];
  const params = [];
  const q = str(req.query.q, 100);
  if (q) {
    where.push("(ref LIKE ? OR title LIKE ? OR leader_name LIKE ? OR email LIKE ? OR institution LIKE ?)");
    params.push(...Array(5).fill(`%${q}%`));
  }
  if (TRACKS.includes(req.query.track)) {
    where.push("track = ?");
    params.push(req.query.track);
  }
  if (CHALLENGES.includes(Number(req.query.challenge))) {
    where.push("challenge = ?");
    params.push(Number(req.query.challenge));
  }
  if (STATUSES.includes(req.query.status)) {
    where.push("status = ?");
    params.push(req.query.status);
  }
  const sql = `SELECT id, ref, created_at, status, track, challenge, title, leader_name, email, phone, institution, city, team_size, file_original, file_size
               FROM registrations ${where.length ? "WHERE " + where.join(" AND ") : ""} ORDER BY created_at DESC LIMIT 1000`;
  const items = (await db.prepare(sql).all(...params)).map((r) => ({
    ...r,
    file_original: decodeName(r.file_original),
  }));
  res.json({ ok: true, items });
});

app.get("/api/admin/registrations/:id", requireAdmin, async (req, res) => {
  const r = await db.prepare("SELECT * FROM registrations WHERE id = ?").get(Number(req.params.id));
  if (!r) return res.status(404).json({ ok: false, error: "not_found" });
  res.json({ ok: true, item: rowToRegistration(r) });
});

app.patch("/api/admin/registrations/:id", requireAdmin, async (req, res) => {
  const b = req.body || {};
  const r = await db.prepare("SELECT id, status, admin_note FROM registrations WHERE id = ?").get(Number(req.params.id));
  if (!r) return res.status(404).json({ ok: false, error: "not_found" });
  const status = STATUSES.includes(b.status) ? b.status : r.status;
  const note = typeof b.admin_note === "string" ? str(b.admin_note, 3000) : r.admin_note;
  await db.prepare("UPDATE registrations SET status = ?, admin_note = ?, updated_at = ? WHERE id = ?").run(status, note, now(), r.id);
  res.json({ ok: true });
});

app.delete("/api/admin/registrations/:id", requireAdmin, async (req, res) => {
  const r = await db.prepare("SELECT id, file_path FROM registrations WHERE id = ?").get(Number(req.params.id));
  if (!r) return res.status(404).json({ ok: false, error: "not_found" });
  if (r.file_path) fs.rm(path.join(UPLOAD_DIR, path.basename(r.file_path)), { force: true }, () => {});
  await db.prepare("DELETE FROM scores WHERE registration_id = ?").run(r.id);
  await db.prepare("DELETE FROM registrations WHERE id = ?").run(r.id);
  res.json({ ok: true });
});

const FILE_TYPES = {
  ".pdf": "application/pdf",
  ".ppt": "application/vnd.ms-powerpoint",
  ".pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
};

function sendProjectFile(res, row, inline) {
  const filePath = path.join(UPLOAD_DIR, path.basename(row.file_path));
  if (!row.file_path || !fs.existsSync(filePath)) return res.status(404).json({ ok: false, error: "not_found" });
  const name = decodeName(row.file_original) || "dossier";
  const ext = path.extname(name).toLowerCase();
  res.setHeader("Content-Type", FILE_TYPES[ext] || "application/octet-stream");
  res.setHeader("Content-Disposition", `${inline && ext === ".pdf" ? "inline" : "attachment"}; filename*=UTF-8''${encodeURIComponent(`${row.ref}_${name}`)}`);
  res.sendFile(filePath);
}

app.get("/api/admin/registrations/:id/file", requireAdmin, async (req, res) => {
  const r = await db.prepare("SELECT ref, file_path, file_original FROM registrations WHERE id = ?").get(Number(req.params.id));
  if (!r) return res.status(404).json({ ok: false, error: "not_found" });
  sendProjectFile(res, r, req.query.inline === "1");
});

const CHALLENGE_TITLES = {
  1: "Océan, Port & Économie bleue",
  2: "Eau, Énergies renouvelables & Transition verte",
  3: "Agriculture, Alimentation & Bioressources",
  4: "Mobilité, Logistique, Connectivité & Territoires intelligents",
  5: "Art, Culture, Tourisme, Sport & Expérience territoriale",
  6: "Entrepreneuriat, Investissement & Nouvelles chaînes de valeur",
};
const CHALLENGE_COLORS = {
  1: "1E9BD7",
  2: "1B8A4B",
  3: "C98B2B",
  4: "5B5FC7",
  5: "C1272D",
  6: "B8652F",
};
const TRACK_COLORS = { idea: "E8A93B", lab: "1E9BD7", scale: "B8652F" };
const PROFILE_LABELS = {
  researcher: "Enseignant-chercheur",
  student: "Étudiant(e)",
  startup: "Startup / Entrepreneur(e)",
};
const LEVEL_LABELS = { master: "Master", doctorate: "Doctorat", engineer: "Cycle d'ingénieur" };
const STATUS_LABELS = {
  received: "Reçue",
  review: "En évaluation",
  shortlisted: "Présélectionnée",
  finalist: "Finaliste",
  winner: "Lauréate",
  rejected: "Non retenue",
};

function buildExportColumns() {
  const cols = [
    ["Référence", (r) => r.ref, 14],
    ["Date", (r) => r.created_at, 20],
    ["Statut", (r) => STATUS_LABELS[r.status] || r.status, 16],
    ["Parcours", (r) => (r.track || "").toUpperCase(), 12],
    ["Challenge n°", (r) => r.challenge, 12],
    ["Challenge thématique", (r) => CHALLENGE_TITLES[r.challenge] || "", 42],
    ["Titre du projet", (r) => r.title, 36],
    ["Acronyme du projet", (r) => r.p.project.acronym, 16],
    ["Acronyme de l'équipe", (r) => r.p.project.team_acronym, 16],
    ["Nom et prénom", (r) => r.leader_name, 24],
    ["Email", (r) => r.email, 28],
    ["Téléphone", (r) => r.phone, 16],
    ["Ville / Région", (r) => r.city || r.p.leader.city, 18],
    ["Profil", (r) => PROFILE_LABELS[r.p.leader.profile] || r.p.leader.profile, 22],
    ["Niveau d'études", (r) => LEVEL_LABELS[r.p.leader.study_level] || "", 16],
    ["Intitulé de formation", (r) => r.p.leader.training_title || "", 28],
    ["Établissement", (r) => r.institution, 40],
    ["Présentation du projet", (r) => r.p.project.summary, 55],
    ["Taille de l'équipe", (r) => r.team_size, 12],
  ];
  for (let i = 0; i < 4; i++) {
    const n = i + 2;
    cols.push(
      [`Membre ${n} - Nom`, (r) => (r.p.members[i] && r.p.members[i].name) || "", 22],
      [`Membre ${n} - Profil`, (r) => PROFILE_LABELS[(r.p.members[i] && r.p.members[i].profile) || ""] || ((r.p.members[i] && r.p.members[i].profile) || ""), 20],
      [`Membre ${n} - Niveau d'études`, (r) => LEVEL_LABELS[(r.p.members[i] && r.p.members[i].study_level) || ""] || "", 16],
      [`Membre ${n} - Formation`, (r) => (r.p.members[i] && r.p.members[i].training_title) || "", 24],
      [`Membre ${n} - Établissement`, (r) => (r.p.members[i] && r.p.members[i].institution) || "", 36]
    );
  }
  cols.push(
    ["Consentement exactitude / participation", (r) => (r.p.consents.rules ? "oui" : "non"), 18],
    ["Consentement communication projet", (r) => (r.p.consents.data ? "oui" : "non"), 18],
    ["Consentement droit à l'image", (r) => (r.p.consents.media ? "oui" : "non"), 18],
    ["Langue du formulaire", (r) => r.lang || "", 10],
    ["Note interne", (r) => r.admin_note || "", 28]
  );
  return cols;
}

function parseReg(row) {
  let payload = { leader: {}, members: [], project: {}, consents: {} };
  try {
    payload = JSON.parse(row.payload || "{}");
  } catch {
    /* payload illisible */
  }
  return {
    ...row,
    p: {
      leader: payload.leader || {},
      members: Array.isArray(payload.members) ? payload.members : [],
      project: payload.project || {},
      consents: payload.consents || {},
    },
  };
}

function fillSheet(sheet, rows, subtitle) {
  const cols = buildExportColumns();
  const EVAL_QUESTION =
    "Cette innovation répond-elle à un défi ou à une opportunité réelle et peut-elle raisonnablement créer de la valeur, être expérimentée, développée ou déployée dans les Provinces du Sud ?";
  sheet.views = [{ state: "frozen", ySplit: 4, xSplit: 1 }];
  sheet.properties.defaultRowHeight = 18;

  sheet.mergeCells(1, 1, 1, cols.length);
  const title = sheet.getCell(1, 1);
  title.value = "Moroccan Sahara Innovation Challenge 2026 — Candidatures";
  title.font = { name: "Calibri", size: 16, bold: true, color: { argb: "FFFFFFFF" } };
  title.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF1A3328" } };
  title.alignment = { vertical: "middle", horizontal: "left", indent: 1 };
  sheet.getRow(1).height = 28;

  sheet.mergeCells(2, 1, 2, cols.length);
  const sub = sheet.getCell(2, 1);
  sub.value = `${subtitle}  ·  Export du ${new Date().toLocaleString("fr-FR")}  ·  ${rows.length} candidature(s)`;
  sub.font = { name: "Calibri", size: 11, italic: true, color: { argb: "FF1A3328" } };
  sub.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF6F0E4" } };
  sub.alignment = { vertical: "middle", indent: 1 };
  sheet.getRow(2).height = 22;

  sheet.mergeCells(3, 1, 3, cols.length);
  const q = sheet.getCell(3, 1);
  q.value = `« ${EVAL_QUESTION} »`;
  q.font = { name: "Calibri", size: 12, italic: true, color: { argb: "FFFFFFFF" } };
  q.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF1A3328" } };
  q.alignment = { vertical: "middle", horizontal: "left", wrapText: true, indent: 1 };
  sheet.getRow(3).height = 36;

  const header = sheet.getRow(4);
  header.height = 32;
  cols.forEach((col, i) => {
    const cell = header.getCell(i + 1);
    cell.value = col[0];
    cell.font = { name: "Calibri", size: 11, bold: true, color: { argb: "FFFFFFFF" } };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFB8652F" } };
    cell.alignment = { vertical: "middle", horizontal: "center", wrapText: true };
    cell.border = {
      top: { style: "thin", color: { argb: "FF8A4A20" } },
      left: { style: "thin", color: { argb: "FF8A4A20" } },
      bottom: { style: "thin", color: { argb: "FF8A4A20" } },
      right: { style: "thin", color: { argb: "FF8A4A20" } },
    };
    sheet.getColumn(i + 1).width = col[2] || 18;
  });

  rows.forEach((raw, idx) => {
    const r = parseReg(raw);
    const row = sheet.getRow(5 + idx);
    const cream = idx % 2 === 0;
    cols.forEach((col, i) => {
      const cell = row.getCell(i + 1);
      const val = col[1](r);
      cell.value = val == null ? "" : val;
      cell.font = { name: "Calibri", size: 10, color: { argb: "FF1A3328" } };
      cell.alignment = {
        vertical: "top",
        wrapText: col[0] === "Présentation du projet" || col[0] === "Établissement" || col[0].includes("Établissement"),
      };
      cell.fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: cream ? "FFFFFBF5" : "FFFFFFFF" },
      };
      cell.border = {
        top: { style: "hair", color: { argb: "FFE2DCCF" } },
        left: { style: "hair", color: { argb: "FFE2DCCF" } },
        bottom: { style: "hair", color: { argb: "FFE2DCCF" } },
        right: { style: "hair", color: { argb: "FFE2DCCF" } },
      };

      if (col[0] === "Parcours" && TRACK_COLORS[String(r.track || "").toLowerCase()]) {
        cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: `FF${TRACK_COLORS[String(r.track).toLowerCase()]}` } };
        cell.font = { name: "Calibri", size: 10, bold: true, color: { argb: "FFFFFFFF" } };
        cell.alignment = { vertical: "middle", horizontal: "center" };
      }
      if (col[0] === "Challenge n°" && CHALLENGE_COLORS[r.challenge]) {
        cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: `FF${CHALLENGE_COLORS[r.challenge]}` } };
        cell.font = { name: "Calibri", size: 10, bold: true, color: { argb: "FFFFFFFF" } };
        cell.alignment = { vertical: "middle", horizontal: "center" };
      }
      if (col[0] === "Établissement" || col[0].endsWith("Établissement")) {
        cell.font = { name: "Calibri", size: 10, bold: true, color: { argb: "FF1A3328" } };
      }
    });
    if (String(r.p.project.summary || "").length > 200) row.height = 60;
  });

  sheet.autoFilter = {
    from: { row: 4, column: 1 },
    to: { row: Math.max(4, 4 + rows.length), column: cols.length },
  };
}

async function buildWorkbook(allRows, { track, challenge } = {}) {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Moroccan Sahara Innovation Challenge 2026";
  wb.created = new Date();

  const filtered = allRows.filter((r) => {
    if (track && r.track !== track) return false;
    if (challenge && Number(r.challenge) !== Number(challenge)) return false;
    return true;
  });

  if (track || challenge) {
    const bits = [];
    if (track) bits.push(`Parcours ${track.toUpperCase()}`);
    if (challenge) bits.push(`Challenge ${challenge} — ${CHALLENGE_TITLES[challenge] || ""}`);
    const name = bits.join(" · ").slice(0, 28) || "Export";
    fillSheet(wb.addWorksheet(name), filtered, bits.join(" · ") || "Export filtré");
    return wb;
  }

  fillSheet(wb.addWorksheet("Toutes"), allRows, "Toutes les candidatures");
  for (const t of TRACKS) {
    fillSheet(wb.addWorksheet(t.toUpperCase()), allRows.filter((r) => r.track === t), `Parcours ${t.toUpperCase()}`);
  }
  for (const n of CHALLENGES) {
    const short = `C${n}`;
    fillSheet(
      wb.addWorksheet(short),
      allRows.filter((r) => Number(r.challenge) === n),
      `Challenge ${n} — ${CHALLENGE_TITLES[n]}`
    );
  }
  return wb;
}

app.get("/api/admin/export.xlsx", requireAdmin, async (req, res) => {
  const track = str(req.query.track, 10).toLowerCase();
  const challenge = Number(req.query.challenge);
  const useTrack = TRACKS.includes(track) ? track : "";
  const useChallenge = CHALLENGES.includes(challenge) ? challenge : null;
  const rows = await db.prepare("SELECT * FROM registrations ORDER BY track ASC, challenge ASC, created_at ASC").all();
  const wb = await buildWorkbook(rows, { track: useTrack, challenge: useChallenge });
  const parts = ["sic2026"];
  if (useTrack) parts.push(useTrack.toUpperCase());
  if (useChallenge) parts.push(`challenge-${String(useChallenge).padStart(2, "0")}`);
  if (parts.length === 1) parts.push("candidatures");
  const filename = `${parts.join("-")}.xlsx`;
  res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
  res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
  await wb.xlsx.write(res);
  res.end();
});

app.get("/api/admin/export.csv", requireAdmin, async (req, res) => {
  const qs = new URLSearchParams();
  if (req.query.track) qs.set("track", String(req.query.track));
  if (req.query.challenge) qs.set("challenge", String(req.query.challenge));
  res.redirect(302, `/api/admin/export.xlsx${qs.toString() ? `?${qs}` : ""}`);
});

app.get("/api/admin/messages", requireAdmin, async (_req, res) => {
  res.json({ ok: true, items: [] });
});

app.use("/api", (_req, res) => res.status(404).json({ ok: false, error: "not_found" }));

app.listen(PORT, async () => {
  try {
    await initDb();
  } catch (e) {
    console.error("Connexion PostgreSQL impossible. Vérifiez DATABASE_URL.", e.message);
    process.exit(1);
  }
  console.log(`Moroccan Sahara Innovation Challenge 2026 - http://localhost:${PORT}`);
  console.log(`Espace administration      - http://localhost:${PORT}/admin`);
});

